---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: weebify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: ghcr.io/serial-experiments-weebify/weebify-media:devops-8f75d48
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: S3_SSL
              value: "YES"
            - name: S3_PORT
              value: "443"
            - name: S3_ENDPOINT
              value: "s3.devops.weebify.tv"
            - name: S3_BUCKET
              value: "weebify"
            - name: SEARCH_HOST
              value: "http://meilisearch:7700/"
            - name: MONGO
              value: "mongodb://admin:admin@mongo:27017/weebify?authMechanism=DEFAULT&authSource=admin"
            - name: AUTH_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: weebify-secrets
                  key: auth-jwt-key
            - name: SEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: weebify-secrets
                  key: meilisearch-master-key
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: weebify-secrets
                  key: minio-user
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: weebify-secrets
                  key: minio-pwd
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: media
  namespace: weebify
spec:
  selector:
    app: media
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
