---
apiVersion: v1
kind: Secret
metadata:
  name: weebify-secrets
  namespace: weebify
type: Opaque
stringData:
  auth-jwt-key: "change-me-in-production"
  meilisearch-master-key: "change-me-in-production"
  minio-user: minioadmin
  minio-pwd: minioadmin

---

# The fact that we need two different Secret objects for minio is horrendous,
# I Blame the Operator... As my coworker says: "Life sucks and then you die"

apiVersion: v1
kind: Secret
metadata:
  name: minio-creds2
  namespace: weebify
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: weebify
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="minioadmin"
    export MINIO_ROOT_PASSWORD="minioadmin"